### ISSUE TITLE
Points on the track

### ISSUE THREAD

**Issue by ivanboychenko** [optiprime/omexport#2]
Hi!
I am really grateful for your code, thanks to it I successfully converted the oruxmapstracks.db into .gpx.

Unfortunately, now I don't see the points that I put in oruxmaps during the journey. 
Has anyone encountered such a problem?

**Comment by optiprime** [comment]
That´s right, because this functionality has not been included yet.  I marked your issue as an enhancement.

**Comment by optiprime** [comment]
I have included track-related waypoints. Please checkout the newest version.

**Comment by ivanboychenko** [comment]
Thank you very much! 
Everything is going well
